<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PlatformTarget>x86</PlatformTarget>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <AssemblyName>OneL</AssemblyName>
    <RootNamespace>OneClickBeautify</RootNamespace>
    <ApplicationIcon>..\OneL.ico</ApplicationIcon>
    <Version>1.0.7</Version>
    <AssemblyVersion>1.0.7.0</AssemblyVersion>
    <FileVersion>1.0.7.0</FileVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <DebugType>none</DebugType>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\AppLauncher.ps1" LogicalName="OneL.AppLauncher.ps1" />
    <EmbeddedResource Include="..\OneL.ico" LogicalName="OneL.OneL.ico" />
  </ItemGroup>
</Project>
